spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: 5236169Zz

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.ky.ClassBrrowSystem.enity